### ISSUE TITLE
Extensions for Beta 4 and earlier will be incompatible

### ISSUE THREAD

**Issue by jordanjay29** [flagrow/bazaar#10]
As there were significant extension changes between Betas 4 and 5 (and to a lesser extent, 5 and 6), anything made for Flarum Beta 4 or earlier is almost guaranteed to be incompatible. We should drop these from being downloaded, it would be too troublesome to manually check which ones might still work. Any authors who find their extension dropped from Bazaar can simply update it if they're still around (and if not, it's probably abandoned).

**Comment by Luceos** [comment]
Very good and sane point, something which should be done before a first release!

**Comment by Luceos** [comment]
This has been fixed in Flagrow.io.
