### ISSUE TITLE
Installed plugin, can not get to its main page

### ISSUE THREAD

**Issue by MostHated** [flagrow/bazaar#105]
### Steps to reproduce

1.  Install the plugin
2. 
3. It won't work.

### Expected behaviour

I have no idea, I was hoping you would be able to tell me?

### Actual behaviour

I click on it on the left side and I get this : 
https://i.imgur.com/VrGOPqE.png

### Configuration

**Operating system:** 
Ubuntu 16
**Version of Bazaar:** 
Whatever the newest one is on 2/10/18
**Version of Flarum:** 
I believe .7?
**Other extensions:** 

From DB : 
["flarum-approval","flarum-bbcode","flarum-emoji","flarum-english","flarum-flags","flarum-likes","flarum-lock","flarum-markdown","flarum-mentions","flarum-sticky","flarum-subscriptions","flarum-suspend","flarum-tags","flagrow-users-list","flagrow-bazaar","datitisev-dashboard"]
<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

This was the most recent log I had just after I tried to access it, not sure if its related.

[2018-02-11 04:38:05] production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /home/u3d/public_html/forum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
Stack trace:
#0 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\DispatchRoute->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#1 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\DispatchRoute), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#2 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#3 /home/u3d/public_html/forum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#4 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\SetLocale->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#5 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\SetLocale), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#6 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#7 /home/u3d/public_html/forum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(36): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#8 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\AuthenticateWithSession->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#9 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\AuthenticateWithSession), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#10 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#11 /home/u3d/public_html/forum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(39): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#12 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\RememberFromCookie->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#13 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\RememberFromCookie), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#14 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#15 /home/u3d/public_html/forum/vendor/flarum/core/src/Http/Middleware/StartSession.php(48): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#16 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\StartSession->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#17 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\StartSession), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#18 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#19 /home/u3d/public_html/forum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(31): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#20 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\ParseJsonBody->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#21 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\ParseJsonBody), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#22 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#23 /home/u3d/public_html/forum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(61): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#24 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\HandleErrors->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#25 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\HandleErrors), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#26 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#27 /home/u3d/public_html/forum/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(111): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#28 /home/u3d/public_html/forum/vendor/flarum/core/src/Http/AbstractServer.php(55): Zend\Stratigility\MiddlewarePipe->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\NoopFinalHandler))
#29 /home/u3d/public_html/forum/vendor/zendframework/zend-diactoros/src/Server.php(157): Flarum\Http\AbstractServer->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Zend\Stratigility\NoopFinalHandler))
#30 /home/u3d/public_html/forum/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\Diactoros\Server->listen(Object(Zend\Stratigility\NoopFinalHandler))
#31 /home/u3d/public_html/forum/index.php(16): Flarum\Http\AbstractServer->listen()
#32 {main}  

</details>

**Comment by clarkwinkelmann** [comment]
Can you try enabling `debug` in `config.php` and try again ? You should have a better error message on the front-end after that.

The logs you copied are sadly completely unrelated (just 404 errors).

**Comment by MostHated** [comment]
I guess it might have been an apache issue. I turned on debug, restarted apache, it started working. I turned debug off, restarted it again, and it seems to be working. Though, is there no way to see an informational page on a plugin before you install it? I can only seem to get an Install option, no info buton or links to any pages?

**Comment by MostHated** [comment]
I just now went to install a plugin (BBCode Pastebin), my install then took my vendor folder, I guess renamed it vendor2, then made a new one that didnt have an autoload.php. I had to rename vendor2 to vendor and restart apache, then my site worked again. Strange.

**Comment by clarkwinkelmann** [comment]
We currently don't offer more details on extensions inside Bazaar. You can check out https://flagrow.io/ for details (which uses the same listing of extensions as Bazaar). In the future Bazaar will show all the details that are available on https://flagrow.io/ as well.

This looks like a timeout or memory issue. Maybe you've got Apache or PHP shutting down the script before it finishes. If you can't raise that limit you can try running tasks in a CRON job instead https://github.com/flagrow/bazaar/wiki/Cron-task-processing

**Comment by luceos** [comment]
Cron based processing hasn't been released yet. It will be available with the next version, which - most likely - will be made available with the next flarum beta.

**Comment by MostHated** [comment]
The first part of my post above is still happening, where it makes a second Vendor folder for some reason when I try to install something.

**Comment by clarkwinkelmann** [comment]
Yes that's normal behavior. Bazaar installs the new dependencies in `vendor2` then switches the folders when ready. If the webserver kills the script (because of memory or timeout) then the `vendor2` will still be there.

Did you find some memory/timeout settings you can increase ?

**Comment by MostHated** [comment]
I increased to 512M but unfortunately still have issues, which is strange. I increased the script execution time as well to 120seconds. I will have to look at what the current error is.

**Comment by MostHated** [comment]
It took about 5-6 minutes of sitting there saying processing, but when I set script execution time to unlimited it finally eventually did load.

**Comment by luceos** [comment]
@MostHated running the task inside the browser is very problematic. The next release offers tasks to be executed in a cron which will resolve this permanently.
