### ISSUE TITLE
UI: Give an icon to extensions without one

### ISSUE THREAD

**Issue by jordanjay29** [flagrow/bazaar#11]
Having extensions with blank icons looks unfavorably on Bazaar (like we are the problem and not the ext). A solution to this could be to assign icons to these extensions manually, perhaps using the first letter of their names?

**Comment by Luceos** [comment]
The issue here is that these extensions use an image as icon. I was already implementing a way to download these images to flagrow.io, but that would require an adapter for every vcs (github, gitlab ..).

**Comment by Luceos** [comment]
This was resolved.
