### ISSUE TITLE
UI: Multiple icons are too close together

### ISSUE THREAD

**Issue by jordanjay29** [flagrow/bazaar#12]
If an extension is both Installed and Enabled, it will show two icons far too close together. This means that on hover, it's hard to get the different pop up messages for description, installed and enabled messages. 

Possible solutions:

1. Combine Install and Enabled icons
2. Make icons bigger

**Comment by Luceos** [comment]
I simply re-used the labels from the avatar, makes sense to rescale them appropriately ;) Feel free to PR too @jordanjay29
