### ISSUE TITLE
Pagination doesn't work at flagrow.io

### ISSUE THREAD

**Issue by Zeokat** [flagrow/bazaar#126]
### Steps to reproduce

1. Go to https://flagrow.io/
2. Use pagination to navigate extensions
3. It doesn't work

### Expected behaviour

Pagination should show paginated results

### Actual behaviour

Nothing, always show same extensions on every page.

### Configuration
**Browser**: FireFox and Chrome

**Comment by luceos** [comment]
I just fixed this, will deploy the update now.
