### ISSUE TITLE
Bazaar Not loading

### ISSUE THREAD

**Issue by huddleberry** [flagrow/bazaar#129]
I installed the plugin but it doesn't display any marketplace apps. Not sure why Can you help

Version of Bazaar: 0.1.0 beta 8
Version of Flarum: Beta 8
![bazaar](https://user-images.githubusercontent.com/27417598/50630326-b590cc80-0f40-11e9-980a-53d47802676d.JPG)

Other extensions: None

**Comment by luceos** [comment]
Open the settings modal inside bazaar and delete the token, then save and refresh the page. Let me know whether that worked for you.

**Comment by huddleberry** [comment]
Baam! It works like a charm.

Thank you
