### ISSUE TITLE
Token field empty

### ISSUE THREAD

**Issue by dartrax** [flagrow/bazaar#148]
### Steps to reproduce

1. Install current version with PocketHold
2. Enable Bazaar
3. The token field is empty
Also, I can't connect (https://github.com/extiverse/bazaar/issues/136)

### Expected behaviour

Token field filled with the corresponding token and a message stating that it is an error if it is empty would be fine. I needed a while to understand why there are no extensions displayed.

### Actual behaviour

No extensions found.

### Configuration

Version of Bazaar: 0.4.1
Version of Flarum: 0.1.0-beta.13
**Other extensions:** 
Clean Install

**Comment by luceos** [comment]
Bazaar is no longer available, see https://discuss.flarum.org/d/5151-bazaar-the-extension-marketplace/273

**Comment by dartrax** [comment]
Aah ok. I didn't know. So I'll have to copy everything to a local place (like xampp I guess), use composer and then load it up again. Still great that I was able to set it up without composer using pockethold as now i'm convinced that it will be worth the effort :)
Good job! Flarum is great!
