### ISSUE TITLE
Issues when installing some extensions.

### ISSUE THREAD

**Issue by AngellitoX** [flagrow/bazaar#15]
Good afternoon guys, I just started testing Bazaar and must admit I'm more than amazed with your work. Although, I have reached an issue. I successfully installed a few extensions but somehow there are some that it won't install.

Here you have the list of the extensions that I couldn't install:

- BBCode Helper
- Chat
- Birthdays
- Flagrow Split
- Widgets

I am running Flarum on a dedicated server with CentOS 7 and just did a composer update to double check and reconfirm my issue.

Hope you can help me! Blessings!

**Comment by Luceos** [comment]
Flagrow split isn't in active development (yet). The version by Davis should be stable though.

Installing these extensions using composer require did work?

**Comment by AngellitoX** [comment]
Ohh, Split from David did work, although the rest remain the same.

Would you be so kind to show me how or where could I get the composer require for those ones?

**Comment by AngellitoX** [comment]
Just installed the following successfully
- Realtime Chat
- Gravatar
- FancyPants

Tried the following without luck:
- Chat
- Widgets
- And the ones in my first post.

I have also updated Baazar to the last version you posted on Flarum, but still the rest is not working. What could be the possible reason?

By the way, I still haven't found the composer commands to try :(

**Comment by jordanjay29** [comment]
I think all the ones you listed are untagged (dev-master version only).

**Comment by Luceos** [comment]
I'm about to drop all dev stability packages from our listings.

**Comment by Luceos** [comment]
https://discuss.flarum.org/d/5151-flagrow-bazaar-the-extension-marketplace/25

**Comment by Luceos** [comment]
@AngellitoX can you confirm this now works in Bazaar? The unstable packages should no longer show up.

**Comment by AngellitoX** [comment]
Confirmed! Sorry for delaying, just woke up. Thank you so much @luceos. Have a wonderful day!
