### ISSUE TITLE
Connect Bazaar installation to Flagrow.io

### ISSUE THREAD

**Issue by Luceos** [flagrow/bazaar#16]
We are automatically creating anonymous oauth personal access tokens for each Bazaar installation so it is able to use our Flagrow.io api. We now need to allow users in Bazaar to connect their Flarum to their accounts so we can enrich their user experience in the future and provide for instance a status dashboard.

**Comment by Luceos** [comment]
Works.

**Comment by mhubregtse** [comment]
I cant seem to save my api token, thats probably why i cant connect to my account?

**Comment by luceos** [comment]
@mhubregtse the token should be automatically added. What are you trying to add as token?
