### ISSUE TITLE
Make official extensions stand out

### ISSUE THREAD

**Issue by clarkwinkelmann** [flagrow/bazaar#19]
Use some color/icon to mark Flarum official extensions as official.

Maybe do a similar thing with Flagrow extensions.

For example we could place a small orange F and a small blue phoenix (the respective logos) beside the vendor names.

**Comment by Luceos** [comment]
Maybe we should ask Darjan to create a design for the marketplace of Bazaar once the design for Flagrow.io is done.

**Comment by luceos** [comment]
vendor based design will be taken care of later
