### ISSUE TITLE
Add update extension link

### ISSUE THREAD

**Issue by clarkwinkelmann** [flagrow/bazaar#22]
The API endpoint for that is ready, but it's not implemented in the UI.

Add a button in the dropdown to update an extension.

Also add a visual indicator that an update is available.

**Comment by Luceos** [comment]
In addition, based on our chat. This should:

- Allow updating Bazaar.
- Set Flarum to maintenance based on a property of our Extension object from Flagrow.io. Flagrow.io will then have a property for extensions `maintenance_preferred` with default `false` which we we enable on Bazaar.
- Make sure to flush the Flarum cache on updating/installing/deleting any extension.

**Comment by clarkwinkelmann** [comment]
Maintenance mode is not really necessary for the composer update itself, because it's a simple folder switch and requests usually finish with the old version and start with the new version afterwards. 

Maintenance mode might be useful while migrations and extensions events are run

**Comment by clarkwinkelmann** [comment]
Given Flarum has no update capability at the moment, we need to choose which actions / events we do upon extension updates. 

For instance we should attempt to run migrations and clear cache. An extension updated event might also be very useful, but it should really be registered in core so you don't need code specific for Bazaar in your extension

**Comment by Luceos** [comment]
Until core has all what we need, I suggest we will implement it ourselves. We can start contributing/moving stuff from Bazaar (and other extensions) to core once our code has become more settled and beta 7 is released (not much will be added to that release anyway and after beta 7 a complete overhaul will take place in preparation of the stable version).

For now we need to run:

- php flarum migrate
- php flarum cache:clear

Triggering an event to listen on makes sense. I'd still suggest setting Flarum to maintenance mode by default or allowing this to be a setting the webmaster can decide on.

**Comment by Luceos** [comment]
- updating of an extension that is restricted by its current version, eg 0.1.0 to 0.2.0 will not work without upping the constraint

**Comment by Luceos** [comment]
Moved update to use require command, but it does not accept the version select yet.
