### ISSUE TITLE
There have some deleted packages 

### ISSUE THREAD

**Issue by skywalker512** [flagrow/bazaar#28]
such as the skywalker512/flarum-ext-simplified-chinese is a deleted packages , but it still apear in bazaar

**Comment by Luceos** [comment]
When did you remove the package?

**Comment by skywalker512** [comment]
yesterday

**Comment by Luceos** [comment]
Packages are deleted after 24 hours if they haven't been found on packagist by then.

**Comment by skywalker512** [comment]
:-O，thanks
