### ISSUE TITLE
Add a way to GET a single extension data from FlagrowIOSearcher

### ISSUE THREAD

**Issue by clarkwinkelmann** [flagrow/bazaar#32]
We use a special `Flagrow\Bazaar\Extensions\Extension` object to merge both local (composer `installed.json`) and remote (flagrow.io) information about an extension.

When installing or updating an extension, we expect the API to return the updated extension data, like here https://github.com/flagrow/bazaar/blob/fa45531846c63769dbbb92803b2f972cebde94a4/src/Api/Controllers/CreateExtensionController.php#L52

This line is not working because 1) the `Flagrow\Bazaar\Extensions\ExtensionManager` object was refactored and 2) because we have no way of crafting a single `Flagrow\Bazaar\Extensions\Extension` object from the `FlagrowIOSearcher`

We need to add a sort of `get` of `find` method to `FlagrowIOSearcher`. This, in turn, requires a way to search the local flagrow.io cache or do individual GET queries to flagrow.io for missing packages

Of course, we can also never return individual data like that.

**Comment by Luceos** [comment]
The ExtensionRepository allows this now.
