### ISSUE TITLE
Not being able to install anything

### ISSUE THREAD

**Issue by 1337god** [flagrow/bazaar#41]
I'm getting this error when trying to install anything on a fresh new install with Bazaar:
![Error 1](https://cdn.discordapp.com/attachments/293845640981774336/303237112818302976/unknown.png)

And with Debug mode on, I click it and it does nothing.
![Error 2](https://cdn.discordapp.com/attachments/293845640981774336/303237900160466954/unknown.png)

forums.postactiv.com's composer.json: https://spit.mixtape.moe/view/3d08d21e

Flarum version: 0.1.0-beta.6
Bazaar version: 0.1.0-beta.5

**Comment by 1337god** [comment]
UPDATE:
I'm dumb, forgot to give permission for composer.json (0777)
`Flagrow\\Bazaar\\Exceptions\\FilePermissionException: Write permission missing for /var/www/forums.postactiv.com/composer.json in`

**Comment by Luceos** [comment]
We need to add documentation that the composer.json file has to be writable by the php user.

**Comment by 1337god** [comment]
GIFS:
https://cdn.discordapp.com/attachments/293845640981774336/303256388132536321/2017-04-16_20-52-05.gif

https://cdn.discordapp.com/attachments/293845640981774336/303257070105526282/2017-04-16_20-53-40.gif

**Comment by 1337god** [comment]
I get this when I click debug
![Error 1](https://cdn.discordapp.com/attachments/293845640981774336/303259842305327105/unknown.png)

**Comment by 1337god** [comment]
UPDATE:
![Error 1](https://cdn.discordapp.com/attachments/293845640981774336/303267324037955585/unknown.png)
Give 0777 permission to both composer.json and composer.lock
And also 0777 permission to the vendor folder.

**Comment by Luceos** [comment]
Added permission information on discuss and in readme.md.
