### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by NFGamerMC** [flagrow/bazaar#47]
Hello,
When I installed this it just said Killed after about 30 seconds. I cd to my install directory

**Comment by NFGamerMC** [comment]
https://imgur.com/gallery/VpHSh

**Comment by Luceos** [comment]
This is a memory issue and has nothing to do with this extension specifically. Please try to resolve this with support on the forums.

Reference: http://stackoverflow.com/questions/20667761/composer-killed-while-updating
