### ISSUE TITLE
Simple but handy feature , search bar

### ISSUE THREAD

**Issue by ibrahimk157** [flagrow/bazaar#53]
It would be really handy if a search bar is added to allow us to simply search whatever extension we want!

**Comment by ibrahimk157** [comment]
Also please add the "feature" tag to this since I don't know how 😅

**Comment by Luceos** [comment]
Only flagrow people can tag ;) A planned overhaul of the Bazaar interface is upcoming which includes a search, eager loading and pagination amongst others.
