### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by wumix** [flagrow/bazaar#55]
Hello i Need a Token for my Website http://wum.cu.cc
Thank you

**Comment by wumix** [comment]
I create a Account on flagrow.io the  Username  is wumix

**Comment by Luceos** [comment]
What version of Bazaar do you run?

**Comment by wumix** [comment]
0.1.0

Daniël Klabbers <notifications@github.com> schrieb am Mo., 8. Mai 2017,
08:28:

**Comment by Luceos** [comment]
- So you see no Token in the settings modal (tripple dot in the Flarum extensions page)?
- Did you seen any errors while enabling Bazaar?
- Can you upgrade Bazaar to the latest 0.1.1? Run:

```bash
composer update flagrow/bazaar
php flarum cache:clear
```

**Comment by wumix** [comment]
Yes i can do it.
Sorry i have a token

Daniël Klabbers <notifications@github.com> schrieb am Mo., 8. Mai 2017,
11:41:

**Comment by Luceos** [comment]
So the issue is resolved?

**Comment by wumix** [comment]
The Token issue is Fixed.
Only the install Extension from Form any Browser is Not Working.
