### ISSUE TITLE
blank

### ISSUE THREAD

**Issue by osnapitzjamie** [flagrow/bazaar#70]
look its just blank with no extensions wtf

![image](https://user-images.githubusercontent.com/16063649/28494101-a7146ea2-6f1c-11e7-961a-2f84a4358ab4.png)

**Comment by luceos** [comment]
Thanks for your report, can you go to the extensions tab and click the triple dot and check whether a token is set?

**Comment by osnapitzjamie** [comment]
There is a token in the box and the save changes button doesnt do anything

**Comment by luceos** [comment]
Can you delete the token in that setting box and save. Then refresh the page hard and open the bazaar tab again?

**Comment by osnapitzjamie** [comment]
still no extensions after doing that

**Comment by luceos** [comment]
We're on top of it.

**Comment by osnapitzjamie** [comment]
now im getting this

![image](https://user-images.githubusercontent.com/16063649/28494379-8861fcd8-6f24-11e7-9e87-93129daf8b35.png)

**Comment by luceos** [comment]
Can you enable debug and see what the debug button on the error popup then shows.

You are running beta 7?

**Comment by osnapitzjamie** [comment]
how do i enable debug and im running watever composer installed i legit installed this today

**Comment by luceos** [comment]
Okay, run:

```
php flarum cache:clear
```

Then extensions should once again show up.

The cause of this issue is that we manually add the latest flarum version to flagrow.io. This information is needed to filter extensions no longer compatible with your flarum installation.

We're going to automate adding new versions of Flarum asap.

**Comment by osnapitzjamie** [comment]
ok ty it works now this can be marked as solved
