### ISSUE TITLE
Extension list not showing all extensions

### ISSUE THREAD

**Issue by hamalrad** [flagrow/bazaar#79]
Hi -
The Bazaar admin page is only showing the first 5 rows of extensions.
(It seems like they are sorted alphabetically, and the last one I see is Beeta Emos UOL)
Search also only finds extensions from within these 5 lines.

### Steps to reproduce

1. Installed Flarum using [pockethold](https://discuss.flarum.org/d/5731-pockethold-a-web-based-installer) 
2. Enable Bazaar
3. Click the Bazaar Tab

### Expected behaviour
See a list of all available extensions 

### Actual behaviour
Only showing the first 5 rows of extensions

**Version of Bazaar:** 0.2.4

**Comment by luceos** [comment]
Woops no pagination buttons. You can still search though 😁 

Thanks for reporting!

**Comment by hamalrad** [comment]
Search only shows results from the extensions shown...i.e, extensions whose names start from A to "Beeta". Can't get search to show anything else.

(I might have a different problem, though, since I can't install any of them. I get a "Your requirements could not be resolved to an installable set of packages" error. Perhaps once I get that solved it'll all work...)

**Comment by luceos** [comment]
@clarkwinkelmann can you do something about this on a short notice?

**Comment by clarkwinkelmann** [comment]
Just confirmed the issue. It's actually a flagrow.io issue, not Bazaar. I'm on it

**Comment by clarkwinkelmann** [comment]
Fix is ready, just waiting for our ops to push it to production :smile_cat:

**Comment by clarkwinkelmann** [comment]
@hamalrad should be fixed now. Don't hesitate to report any new issue.

Thanks again for your report !

**Comment by hamalrad** [comment]
Thanks!
All extensions showing now :-)
