### ISSUE TITLE
Can't login the admin panel after enable this extension

### ISSUE THREAD

**Issue by sulf1ron** [flagrow/bazaar#89]
I'm using flarum beta7.
But after I install and enable this extenion, I was redirected to nojs=1 and couldn't use the admin panel any more. The forum became no js as well.
I tried to cleared both server and browser' cache but nothing changed.

**Comment by luceos** [comment]
Anything showing up if you set `false` to `true` in your `config.php` after `debug`?

**Comment by sulf1ron** [comment]
It just became OK after I set to debug mode.
So weird!
I also installed byobu, and the same occurred.
Now I knew how to deal with the problem, but what caused it? Curious to know.

**Comment by luceos** [comment]
You have to clear the cache of Flarum, your browser and if you use CloudFlare that one too.

Clearing the cache of Flarum:

```
php flarum cache:clear
```
